services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
            args:
                - BUILDKIT_INLINE_CACHE=1
        container_name: travstats-backend
        dns:
            - 8.8.8.8
            - 1.1.1.1
        ports:
            - "3000:3000"
        env_file:
            - ./backend/script/.env
        volumes:
            - ./backend:/app
            - /app/node_modules
        networks:
            - travstats-network
        restart: unless-stopped

    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        container_name: travstats-frontend
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - backend
        networks:
            - travstats-network
        restart: unless-stopped

networks:
    travstats-network:
        driver: bridge
